filter:
    excluded_paths: ['tests/*', 'vendor/*']

build:
    environment:
        php: '5.6'
        php: '7.0'
    tests:
        override:
            -
                command: 'php vendor/bin/phpunit'
                coverage:
                    file: 'build/logs/coverage.xml'
                    format: 'php-clover'

checks:
    php:
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"