language: php

# list any PHP version you want to test against
php:
  - 7.0
  - 5.6
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: vendor/bin/phpunit